# Generated by Django 5.2.8 on 2025-11-12 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם תגית')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='כותרת')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='תאריך יעד')),
                ('priority', models.CharField(choices=[('H', 'גבוהה'), ('M', 'בינונית'), ('L', 'נמוכה')], default='M', max_length=1, verbose_name='עדיפות')),
                ('status', models.CharField(choices=[('new', 'חדשה'), ('in_progress', 'בתהליך'), ('done', 'הושלמה')], default='new', max_length=20, verbose_name='סטטוס')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='tasks.task', verbose_name='משימת אב')),
                ('tags', models.ManyToManyField(blank=True, to='tasks.tag', verbose_name='תגיות')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='משתמש')),
            ],
            options={
                'ordering': ['due_date', 'priority'],
            },
        ),
    ]
